apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: sc-local-storage
    namespace: jenkins
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
