apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre
  namespace: postgre  
spec:
  storageClassName: sc-local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi