apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: sc-local-storage
    namespace: jenkins
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
#reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: jenkins
    namespace: jenkins
    labels:
        type: jenkins
spec:
    claimRef:
        name: jenkins
        namespace: jenkins
    storageClassName: sc-local-storage
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/share_data/jenkins'
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: jenkins-gradle
    namespace: jenkins
spec:
    claimRef:
        name: jenkins-gradle
        namespace: jenkins
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    storageClassName: sc-local-storage
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: '/share_data/jenkins-gradle'
