apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: jenkins  
  labels:
    type: jenkins 
spec:
  storageClassName: jenkins 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/share_data/jenkins"
