apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: jenkins  
  labels:
    type: jenkins 
spec:
  storageClassName: jenkins 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/share_data/jenkins"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-local-storage
  namespace: jenkins
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer