apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jenkins-gradle
    namespace: jenkins
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 10Gi
    storageClassName: sc-local-storage
